### ISSUE TITLE
Build Hack Night Page

### ISSUE THREAD

**Issue by zenlex** [tulsawebdevs/website#15]
We should build some sort of flow/pages for our hack night events and resources. The need here is twofold for now: 
1) We specifically need a page to layout our Greenfield Democracy! hack night as both a real need and a test case
2) We should do so in such a way that we end up with some useful template(s)/guidance/docs/ui for building future hack night pages

**Comment by helmturner** [comment]
Thinking about features for this, there are basically 3 high-level user stories here:

- As a pro

**Comment by helmturner** [comment]
Thinking about features for this, here are my thoughts on user stories—some of it is a bit forward thinking. @deino475 @zenlex  @CKCarr I'd love to hear some feedback. In the meantime I'll start on the higher priority stuff. 

1. As a prospective attendee, I should be able to find information and resources useful for preparing for the event, including:
	a. Information on the overall nature of the events [**(Ⅰ)**](./#Ⅰ-Higher-Priority)
	b. examples of previous activities [**(Ⅱ)**](./#Ⅱ-Moderate-Priority)
	c. Specific information about the next event's 'warm-up' lab [**(Ⅰ)**](./#Ⅰ-Higher-Priority)
	d. The general state of active projects relevant to the next event [**(Ⅲ)**](./#Ⅲ-Deferred-Priority)
	e. Tips for onboarding / making the most of my time [**(Ⅲ)**](./#Ⅲ-Deferred-Priority)

2. As an attendee, I should be able to access the materials and submit ideas/work as I participate, such as:
	a. A place to submit lab results and view submissions from others [**(Ⅱ)**](./#Ⅱ-Moderate-Priority)
	b. Links to projects/collaboration tools used in active projects (GH project/repos, figma, trello, etc) [**(Ⅲ)**](./#Ⅲ-Deferred-Priority)

3. As an prior attendee, I should be able to find/share my contributions [**(Ⅱ)**](./#Ⅱ-Moderate-Priority)

4. As an active participant in a project, I should find useful collaboration tools to facilitate contributing [**(Ⅴ)**](./#Ⅳ-Non-Priority)

5. As a stakeholder in an active project, I should have a place to find relevant updates/calls to action [**(Ⅳ)**](./#Ⅳ-Backlogged-Priority)


<br>

#### Ⅰ. Higher Priority

Given existing copy/discussions I think these are low lifts, and they provide immediate value for the next hack-night

#### Ⅱ. Moderate Priority

These could be useful for the next hack night, but are potentially broad in scope. Most of these user stories are satisfied by GitHub features, but that could be said for all of them, and well... we're building a website for a reason 😸 

That does mean, however, that we have a v0 for them and can simply link to GitHub to start out. A blog with photos/links might be an easy upgrade.

#### Ⅲ. Deferred Priority

I don't see anything we can do on these until we've established some conventions in our first few iterations.

#### Ⅳ. Backlogged Priority

We're not at a point that this is relevant yet, but as we involve stakeholders this will become more important. Like many of these items, a blog might be a good first step.

#### Ⅴ. Non-priority

For more involved/active members, I think (and vaguely remember a conversation along these lines) that it should be a goal to *encourage* the use of the tools (GitHub, etc.). Reasons being a) they are more incentivized to do so and b) it's something they should probably learn if they're not familiar.

**Comment by helmturner** [comment]
I took a stab at integrating react by adding a tabs component. One gotcha @CKCarr and I discovered is that, once you pick a rendering framework, you have to use that same framework all the way down the component tree. It's possible to create one island with e.g React and another with Vue, but you composing them vertically isn't possible (at least, not without some fancy engineering). It *is* possible to compose them horizontally by [using nanostores to share state](https://docs.astro.build/en/recipes/sharing-state-islands/), however.

It's implemented with a healess library so it's still completely unstyled, but we don't have much direction on design so I didn't want to bother too much with styling. The accessibility story is also buggy right now due to broken element ids, but I know the source of the issue and just need to try a couple fixes.

**Comment by zenlex** [comment]
I love this. Nice work. My only real thought/suggestion on the stories is I think we might want to make projects a "node" so to speak so that from hack night page it's easy to get to a projects dashboard, but I think if we do enough cool stuff integrating all those project resources at the root of the hack night page could get overwhelming and the project stuff specifically seemed like the next biggest grouping after the "event" stuff.

**Comment by zenlex** [comment]
Adding @CKCarr as an assignee on this since she mentioned working on the hero copy and such.

**Comment by helmturner** [comment]
> I love this. Nice work. My only real thought/suggestion on the stories is I think we might want to make projects a "node" so to speak so that from hack night page it's easy to get to a projects dashboard, but I think if we do enough cool stuff integrating all those project resources at the root of the hack night page could get overwhelming and the project stuff specifically seemed like the next biggest grouping after the "event" stuff.

Sounds like a job for an accordion component... what do you think?
