### ISSUE TITLE
Bootstrap Style System

### ISSUE THREAD

**Issue by helmturner** [tulsawebdevs/website#21]
We need the 'nuts-and-bolts' in place to minimize the need for contributors to implement design when adding features, while also enabling anyone more design-inclined to contribute without the need to code anything.

After [much back and forth](https://techlahoma.slack.com/archives/C061ADYPHNJ/p1708206764328509), we've landed on [Vanilla Extract](https://vanilla-extract.style/) with [Recipes](https://vanilla-extract.style/documentation/packages/recipes/), with [Rainbow Sprinkles](https://github.com/wayfair/rainbow-sprinkles) for in-line styles.

This gives us the benefits of a style system and type-safety with little effort up front, while also avoiding the [pitfalls of CSS-in-JS](https://blog.mayank.co/is-css-in-js-actually-bad).

**Comment by zenlex** [comment]
Keeping it simple for now lets reference what exists in https://github.com/tulsawebdevs/twd-branding for colors, typefaces, logos, etc.
