### ISSUE TITLE
Architect Auth flow

### ISSUE THREAD

**Issue by zenlex** [tulsawebdevs/website#24]
- Need to design/implement user registration form (Will use OAuth with GitHub for actual auth, but need moderation flow for verifying users)
- Need to determine what user data we intend to persist / make available to microservices (while maintaining bounded contexts)
- Figure out backing service setup / needs (Redis, DB, etc.) or JWT flow
- Decide on protocol for microservices using session data vs state.

**Comment by helmturner** [comment]
We considered implementing Auth.js on the front-end and a redis-based session store, but as you mentioned, at some point down the road we'll probably be managing plumbing between a number of different services and applications with various stacks.

RE: Your suggestion of Clerk, that's probably our best bet. It's build on top of Auth.js (they maintain the library now), and it comes with integrations for just about everything we might need. It's built on open source, so if we need anything they don't have we can do it. Plus, in my experience, they've always been quite responsive and quick to add requested features!

**Comment by zenlex** [comment]
In the interest of following my own advice about not building stuff we don't need until we need it, here's where I'm thinking we'll start:
- Use Clerk for Auth and Session management. 
- API gateway ingress will validate the JWT/Session from Clerk
- Have a 'Users' microservice built into the API gateway that hits a redis cache with persistence 
  - Key = GH username, Val = JSON where root level keys are microservice names
  - Microservices can read/write to the users service via requests to the gateway, gateway will manage tying user to service data (limited size data - large/complex datasets should be handled by backing services bound to the individual microservice)
  - Astro app can also hit the /users service on the API gateway to retrieve additional user information (like role) beyond what's in the JWT from Clerk.
 
The basic idea is we offload all the browser session management and auth to Clerk, but handle microservice session data and user profiles at the gateway level. Then the frontend has no real auth responsibilities at all except the Oauth flow/JWT passing.

**Comment by zenlex** [comment]
I made a thing:
![image](https://github.com/tulsawebdevs/website/assets/39918654/8c4c0d8f-da5d-484c-8f47-f689c6e943db)

**Comment by zenlex** [comment]
I made a picture of my previous word salad 😅 
![image](https://github.com/tulsawebdevs/website/assets/39918654/30bd4aa4-3796-4ac4-a972-e26a50efb3b0)

**Comment by zenlex** [comment]
I made a picture of my word salad 😅 
![image](https://github.com/tulsawebdevs/website/assets/39918654/22a1ce99-f82c-411a-999c-5aeec96b861e)

**Comment by helmturner** [comment]
LGTM, but when are you hoping to have this shipped? Are you trying for this by Tuesday?

**Comment by helmturner** [comment]
This is working, and I think being tracked in another repo. Going to close this for now, feel free to reopen if necessary.
