### ISSUE TITLE
HMR doesn't work in docker development environment

### ISSUE THREAD

**Issue by helmturner** [tulsawebdevs/website#56]

**Comment by friedsquiggles** [comment]
HMR is working for me when running docker dev env.

I am able to make simple content and css changes and see them reflected on their pages immediately after saving. I am also able to add `.astro` files to `/pages/` and route to them in my browser without reloading docker-compose.

- macos 14.2.1
- docker engine 25.0.3
- docker compose v2.24.5-desktop.1
- arc browser 1.31.2

**Comment by zenlex** [comment]
@helmturner HMR is working fine for me as well
- ubuntu 22.04 (WSL2 under Windows 11)
- docker desktop 4.23.0
- docker engine 24.0.6
- docker compose v2.21.0-desktop.1
- firefox browser (dev edition) 124.0b7

Going to close this as wontfix unless someone actually has a repro...
