### ISSUE TITLE
Edit CONTRIBUTING.md

### ISSUE THREAD

**Issue by zenlex** [tulsawebdevs/website#7]
- [x] Move over any useful astro instructions from README.md
- [x] Add branch naming conventions / git flow / branch rules
- [x] Add conventional commits tl;dr and link
- [x] Add testing expectations
- [x] Add process for developing/deploying/documenting microservices (separate repos - linked)
- [x] Add CI flow description 
- [x] Add pre-commit setup description

**Comment by CKCarr** [comment]
pre-commit setup description: In creating the documentation for this I noticed it mentions setting up the .pre-commit-config.yaml.
We do not currently have one. 
[pre-commit](https://pre-commit.com/) - I noticed here under quickstart #2 you can generate a very basic configuration using [pre-commit sample-config](https://pre-commit.com/#pre-commit-sample-config)
I ran through this setup and created the config for myself to test. 
Should I include this config with the push of issue #7?
