### ISSUE TITLE
feat: Voting Component

### ISSUE THREAD

**Issue by helmturner** [tulsawebdevs/website#96]
We need to give members a way to vote! For that, we need a voting component.

Requirements:
 - Should take a proposal ID and Title as props
 - Should allow users to cast or update votes for the given proposal
 - May also take a Title prop to display on the component
 - Does not need to be styled (yet)
 - Should handle errors (see the [api docs](https://www.tulsawebdevs.org/docs/api))

Also, see additional requirements in this comment: https://github.com/tulsawebdevs/website/issues/96#issuecomment-2081584241

**Comment by zenlex** [comment]
This may be implied, but would be lovely for this to work on the index such that as a user I could see all available proposals and vote on them right on the index screen without having to click through to the proposal detail.

**Comment by zenlex** [comment]
@helmturner This will also need some type of currentVote optional prop to show the current vote if present for that user won't it?

**Comment by helmturner** [comment]
Yeah, I limited the scope of this to just a component so that component can be embedded in cards if we choose.

> @helmturner This will also need some type of currentVote optional prop to show the current vote if present for that user won't it?

Hmm, maybe—but not with the API as it is. Currently there is no `GET /votes` or the like, and votes are not returned with proposals by default. Getting vote information for a proposal requires a separate request to `GET /proposals/{id}/votes`. 

The way it's currently designed, it would make sense for the component to fetch the vote totals internally. Do you think we should add an API endpoint for bulk voting data?

**Comment by helmturner** [comment]
A couple of clarifications on the spec:

- The :thumbsup: :thumbsdown: indicators should only show total vote counts for closed proposals (voting finished)

- For open (in voting) proposals, they may show the user’s current vote, i.e.:
	-  [+1 :thumbsup:] [ 0 :thumbsdown:] ….(click down *2)….[ 0 :thumbsup:] [-1 :thumbsdown:]
- The :thumbsup: :thumbsdown: buttons may be used to control the radio button value by moving it left or right, but the radio button should be the source of truth for the vote value. If the radio button changes, the :thumbsup: :thumbsdown: buttons should update their displayed values to reflect that
- Requests should be debounced such that rapidly changing a vote doesn’t send too many requests to the server
